### PR TITLE
Create fa.js (support Persian/Farsi language)

### PR DESCRIPTION
**Pull request by erfanatp**
This file is translated to Persian/Farsi. Please add it into the project.

### CODE REVIEW

**Comment by victorjonsson** [comment]
Great but you need the , sign to real comma symbols ","

**Comment by victorjonsson** [comment]
Okey, now it says that `دو` will be removed in most browsers? Can you change it tom somehtingelse?

**Comment by erfanatp** [comment]
OK. It wasn't necessary. I removed it.

**Comment by victorjonsson** [comment]
Super!

**Pull request merged**
