### PR TITLE
grecaptcha validatorFunction fixed

### PR DESCRIPTION
**Pull request by FuzzyBS**
`validatorFunction` should return a `boolean`. 
`grepcaptcha.getResponse()` returns a `string`, so I added `!=''` to check if string is empty.

Hopefully this will fix it so the submit button stays disabled until user has completed the CAPTCHA otherwise this validator serves no purpose other than to generate the field to submit with the form data.

### CODE REVIEW

**Comment by victorjonsson** [comment]
Superb!

**Comment by arkin-** [comment]
Thanks @FuzzyBS, this was causing problems for me. I'll give it a go.

**Comment by FuzzyBS** [comment]
Glad I could contribute. This is my first time contributing on github so any pointers would be appreciated.

I'm thinking we should add a CSS rule to the default theme so it sizes the field the same as the actual CAPTCHA will be with visible text indicating that they need to reload or there was an error (i.e. javascript disabled). This way if the CAPTCHA doesn't load for some reason, or loads late, the user will know why there's an extra field with no label.

Also, the documentation needs to be fixed up. The input field should have the site key, not the ID of the CAPTCHA div (which will be set by the script after it loads). This had me very confused at first. It would also be helpful to show the CAPTCHA in the example at the bottom of the security module page.

`<input data-validation="recaptcha" data-validation-recaptcha-sitekey="...">`

Hope this helps. Thanks for the feedback. (c:

**Comment by FuzzyBS** [comment]
@victorjonsson, 
Just curious, how long does it usually take before the new version becomes available on CDNJS?

**Pull request merged**
