### PR TITLE
added size option to Google reCaptcha

### PR DESCRIPTION
**Pull request by FuzzyBS**
As an attribute:
`data-validation-recaptcha-size="compact|normal"`

As a config parameter:
`reCaptchaSize: "compact|normal"`

### CODE REVIEW

**Comment by goatandsheep** [comment]
@FuzzyBS you'll need to pull and try again :frowning:

**Comment by FuzzyBS** [comment]
Sorry...github confuses me somewhat. Did I fix my issue and do it right this time? Thanks @goatandsheep

**Comment by goatandsheep** [comment]
I think so?? Did you need help with GitHub? Ask any questions to clarify any troubles you were having with it.

**Comment by FuzzyBS** [comment]
I guess some of it is just getting use to git and github terminology, but what I think messed me up was when I used github windows and adobe brackets to work on it and tried to use the grunt file and node-js to build it and make a minified version of security.js to use on my site until this gets to the CDN. However, the file it generated was just a diff of the affected file, not the actual contents. But now I'm guessing I shouldn't be building on my computer but should rather let you guys handle that until I know what's what. So really, I just need to get more familiar with node-js, grunt, and the whole workflow of developing this way. At some point, I'm hoping I can refine/fix some of the extensions/plug-ins for Adobe Brackets.

Anyway, I'm glad to contribute what I can anywhere I can. My next venture into this particular project will be to write a wiki page demonstrating the use of the Google reCaptcha because that's the part of the documentation that was spotty when I was looking for it.

Alright, I'll shut up now. Time to get back to work anyway. Thanks again, @goatandsheep .

Bruce

**Comment by victorjonsson** [comment]
Awesome! Your contributions are greatly appreciated. 

I'll take a look at this and try to have it merged as soon as possible.

**Comment by FuzzyBS** [comment]
@victorjonsson I'm having trouble creating the wiki page on your project. It's giving me a 500 server error, so I don't know if it's because of permissions or something.

Anyway, I've got the wiki for Google reCaptcha done on my fork, and I'd be happy for you to copy it to yours, however that is done. Also please feel free to include any of the info in the documentation on your website or in the README.md.

While fact-checking this I also discovered one other option for Google reCaptcha which is audio or image, so if I get around to it today I'll try to add that so it can make it into the next pull for distro.

Ironically, after adding this option I decided I didn't want to use the compact size on my site after, but I'm sure someone will someday and I was already familiar with the code.

**Comment by FuzzyBS** [comment]
Type of reCaptcha to render, image or audio. (defaults to image)

HTML attribute:
`data-validation-recaptcha-type="image|audio"`

JS config setting:
`reCaptchaSize: 'image|audio'`

**Pull request merged**
