### PR TITLE
Ability to force validation of single hidden element

### PR DESCRIPTION
**Pull request by Igloczek**
I think it's useful to have ability to force validation of single hidden input - in my case for `select` elements generated by Select2.js lib.

How to use:
Add `data-force-validation-if-hidden="true"` and global settings will be ignored.

### CODE REVIEW

**Comment by xdragus** [comment]
Any update when this merge will be is resolved and this feature added?

**Comment by victorjonsson** [comment]
Attr `force-validation-if-hidden` must be prefixed `validation-`. Use `$(...).valAttr('')` instead of `$(...).data('')`

**Comment by Igloczek** [comment]
Whare can I find the implementation of `valAttr` method? It's not in jQuery API docs and doesn't looks like a custom method too.

**Comment by victorjonsson** [comment]
https://github.com/victorjonsson/jQuery-Form-Validator/blob/master/src/main/jquery-plugins.js#L284

**Comment by Igloczek** [comment]
Changed to `valAttr `.

**Comment by Amedeo91** [comment]
This PR is merged and adapted here: https://github.com/Amedeo91/jQuery-Form-Validator

**Pull request closed without merging**
